In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# verileri okuyalım
veriler=pd.read_csv('input/veriler.csv')
print(veriler)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k


## Veri Ön İşleme

In [3]:
boy=veriler[['boy']]
boyKilo=veriler[['boy','kilo']]
print(boyKilo)

    boy  kilo
0   130    30
1   125    36
2   135    34
3   133    30
4   129    38
5   180    90
6   190    80
7   175    90
8   177    60
9   185   105
10  165    55
11  155    50
12  160    58
13  162    59
14  167    62
15  174    70
16  193    90
17  187    80
18  183    88
19  159    40
20  164    66
21  166    56


### Eksik Veriler
* sci - kit learn

In [4]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
'''
from sklearn.impute import SimpleImputer:

    Bu satır, scikit-learn kütüphanesinin impute modülünden SimpleImputer sınıfını içe aktarır. Bu sınıf, eksik verileri belirli bir stratejiye göre doldurmak için kullanılır.

imputer = SimpleImputer(missing_values=np.nan, strategy='mean'):

    SimpleImputer(missing_values=np.nan, strategy='mean'): Bu, SimpleImputer sınıfından bir örnek oluşturur.
        missing_values=np.nan: Eksik değerlerin NaN (Not a Number) olduğunu belirtir. Yani, NaN olan hücreler eksik veri olarak kabul edilir.
        strategy='mean': Eksik değerlerin doldurulma stratejisini belirtir. Burada, eksik değerler ilgili sütunun " ortalama değeri " ile doldurulacaktır.
'''

'\nfrom sklearn.impute import SimpleImputer:\n\n    Bu satır, scikit-learn kütüphanesinin impute modülünden SimpleImputer sınıfını içe aktarır. Bu sınıf, eksik verileri belirli bir stratejiye göre doldurmak için kullanılır.\n\nimputer = SimpleImputer(missing_values=np.nan, strategy=\'mean\'):\n\n    SimpleImputer(missing_values=np.nan, strategy=\'mean\'): Bu, SimpleImputer sınıfından bir örnek oluşturur.\n        missing_values=np.nan: Eksik değerlerin NaN (Not a Number) olduğunu belirtir. Yani, NaN olan hücreler eksik veri olarak kabul edilir.\n        strategy=\'mean\': Eksik değerlerin doldurulma stratejisini belirtir. Burada, eksik değerler ilgili sütunun " ortalama değeri " ile doldurulacaktır.\n'

In [5]:
# Eğer elimdeki veri setinde yas sütununda eksik olsaydı o kısmı ortalama değer ( mean ) ile doldurmuş olacaktım
Yas=veriler.iloc[:,1:4].values
imputer=imputer.fit(Yas[:,1:4])
print(Yas)

[[130  30  10]
 [125  36  11]
 [135  34  10]
 [133  30   9]
 [129  38  12]
 [180  90  30]
 [190  80  25]
 [175  90  35]
 [177  60  22]
 [185 105  33]
 [165  55  27]
 [155  50  44]
 [160  58  39]
 [162  59  41]
 [167  62  55]
 [174  70  47]
 [193  90  23]
 [187  80  27]
 [183  88  28]
 [159  40  29]
 [164  66  32]
 [166  56  42]]


## Regresyon oluşturabilmek için numeric değerlere ihtiyacım var bu sebepten cinsiyet ve üşke kolonlarındaki değerleri değiştireceğiz<br>
## Encoding kullanacağız.<br>
* encoder: Kategorik -> Numeric

### Cinsiyet için :

In [6]:
# cinsiyet yerine c şeklinde isimlendirdik
c=veriler.iloc[:,-1:].values
'''
veriler.iloc[:,-1:]:

    iloc[] yöntemi, Pandas DataFrame'deki satır ve sütunları konumlarına göre seçmeye yarar.
    : ifadesi, tüm satırları seçtiğimizi belirtir.
    -1: ifadesi, en son sütunu seçer. : kullanımıyla birlikte en sondan başlayarak (yalnızca bir sütun olduğu için) bu sütunu seçer.

Bu adımda, veriler DataFrame'inin tüm satırlarının son sütunu seçiliyor.

.values:

    .values özelliği, Pandas DataFrame'i veya Serisini bir NumPy dizisine dönüştürür.

Bu adımda, seçilen son sütunu bir NumPy dizisi haline getiriyoruz.
'''
print(c)

[['e']
 ['e']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['k']
 ['k']]


In [7]:
from sklearn import preprocessing # Bu modül, veri ön işleme (preprocessing) işlemleri için çeşitli araçlar sunar.
le=preprocessing.LabelEncoder()
# LabelEncoder sınıfından bir örnek oluşturuyoruz. LabelEncoder, kategorik verileri sayısal verilere dönüştürmek için kullanılır.
# Örneğin, ["kırmızı", "yeşil", "mavi"] gibi kategorik değerleri [0, 1, 2] gibi sayısal değerlere dönüştürür.
c[:,-1]=le.fit_transform(veriler.iloc[:,-1])
'''
c[:,-1] = le.fit_transform(veriler.iloc[:,-1]):

    veriler.iloc[:,-1]: Bu, veriler DataFrame'inin son sütununu seçer. iloc yöntemi, DataFrame'in belirli bir dilimini seçmek için kullanılır.
    le.fit_transform(...): fit_transform yöntemi, önce etiket kodlayıcısını kategorik verilerle eğitir (fit), ardından bu verileri sayısal değerlere dönüştürür (transform).
    c[:,-1] = ...: c NumPy dizisinin son sütununa, dönüştürülmüş sayısal değerler atanır.
'''
print(c)

[[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]


In [8]:
ohe=preprocessing.OneHotEncoder()
c=ohe.fit_transform(c).toarray()
'''
Bu kod parçası, LabelEncoder ile sayısal değerlere dönüştürülmüş olan kategorik verileri, OneHotEncoder kullanarak tekil (one-hot) kodlamaya dönüştürüyor. Adım adım açıklayalım:
ohe = preprocessing.OneHotEncoder():

    OneHotEncoder sınıfından bir örnek oluşturuyoruz. OneHotEncoder, kategorik verileri ikili (binary) vektörlere dönüştürmek için kullanılır. 
    Örneğin, 0, 1 ve 2 gibi sayısal kategorileri şu şekilde vektörlere dönüştürür: [1,0,0], [0,1,0] ve [0,0,1].

c = ohe.fit_transform(c).toarray():

    fit_transform(c): OneHotEncoder'ı veri seti c ile eğitir (fit) ve ardından bu verileri one-hot kodlamalı vektörlere dönüştürür (transform).
    toarray(): Bu, elde edilen sparse matrisini (seyrek matris) yoğun (dense) bir NumPy dizisine dönüştürür.
    Bu, verilerin kolayca işlenebilmesi ve analiz edilebilmesi için gereklidir.
'''
print(c)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


### Ülke için :

In [9]:
ulke=veriler.iloc[:,0:1].values
ulke[:,0]=le.fit_transform(veriler.iloc[:,0])
ohe=preprocessing.OneHotEncoder()
ulke=ohe.fit_transform(ulke).toarray()
print(ulke)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [10]:
# Numpy dizileri dataframe donusumu
sonuc=pd.DataFrame(data=ulke,index=range(22),columns=['fr','tr','us'])
sonuc2=pd.DataFrame(data=Yas,index=range(22),columns=['boy','kilo','yas'])
cinsiyet=veriler.iloc[:,-1].values
sonuc3=pd.DataFrame(data=c[:,:1],index=range(22),columns=['cinsiyet']) # hem 0 hem 1 kolonunu almamamız lazım o kısım çok önemli
print(sonuc3)

    cinsiyet
0        1.0
1        1.0
2        0.0
3        0.0
4        1.0
5        1.0
6        1.0
7        1.0
8        0.0
9        1.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       1.0
16       1.0
17       1.0
18       1.0
19       0.0
20       0.0
21       0.0


## DataFrame Birleştirme İşlemi

In [11]:
s=pd.concat([sonuc,sonuc2],axis=1)
'''
s = pd.concat([sonuc, sonuc2], axis=1):

    pd.concat(): pandas kütüphanesindeki concat fonksiyonu, iki veya daha fazla DataFrame'i birleştirmek için kullanılır.
    [sonuc, sonuc2]: Bu, birleştirilecek olan iki DataFrame'i içeren bir listedir.
    axis=1: Bu parametre, birleştirmenin sütun bazında yapılacağını belirtir. Yani, sonuc ve sonuc2 DataFrame'leri yatay olarak yan yana eklenir.
    s: Bu, birleştirilmiş yeni DataFrame'i tutan değişkendir.
'''
s2=pd.concat([s,sonuc3],axis=1)
print(s2)

     fr   tr   us  boy  kilo  yas  cinsiyet
0   0.0  1.0  0.0  130    30   10       1.0
1   0.0  1.0  0.0  125    36   11       1.0
2   0.0  1.0  0.0  135    34   10       0.0
3   0.0  1.0  0.0  133    30    9       0.0
4   0.0  1.0  0.0  129    38   12       1.0
5   0.0  1.0  0.0  180    90   30       1.0
6   0.0  1.0  0.0  190    80   25       1.0
7   0.0  1.0  0.0  175    90   35       1.0
8   0.0  1.0  0.0  177    60   22       0.0
9   0.0  0.0  1.0  185   105   33       1.0
10  0.0  0.0  1.0  165    55   27       0.0
11  0.0  0.0  1.0  155    50   44       0.0
12  0.0  0.0  1.0  160    58   39       0.0
13  0.0  0.0  1.0  162    59   41       0.0
14  0.0  0.0  1.0  167    62   55       0.0
15  1.0  0.0  0.0  174    70   47       1.0
16  1.0  0.0  0.0  193    90   23       1.0
17  1.0  0.0  0.0  187    80   27       1.0
18  1.0  0.0  0.0  183    88   28       1.0
19  1.0  0.0  0.0  159    40   29       0.0
20  1.0  0.0  0.0  164    66   32       0.0
21  1.0  0.0  0.0  166    56   4

## Verilerin Eğitilmesi ve Test İçin Bölünmesi

In [12]:
from sklearn.model_selection import train_test_split
# Bu satır, scikit-learn kütüphanesinden train_test_split fonksiyonunu içe aktarır. Bu fonksiyon, veri setlerini eğitim ve test setlerine ayırmak için kullanılır.
x_train,x_test , y_train,y_test=train_test_split(s,sonuc3,test_size=0.33,random_state=0)
'''
train_test_split(s, sonuc3, test_size=0.33, random_state=0): Bu, s ve sonuc3 veri setlerini eğitim ve test setlerine ayırır.

    s: Özellikleri (features) temsil eden DataFrame.
    sonuc3: Hedef değişkeni (labels) temsil eden DataFrame.
    test_size=0.33: Verilerin %33'ünün test setine, geri kalan %67'sinin eğitim setine ayrılacağını belirtir.
    random_state=0: Rastgelelik kontrolü için sabit bir rastgelelik durumunu belirler. Bu, aynı verilerle aynı sonuçları elde etmek için kullanılır.
'''
print("x_train :")
print(x_train)
print("x_test :")
print(x_test)
print("y_train :")
print(y_train)
print("y_test :")
print(y_test)

x_train :
     fr   tr   us  boy  kilo  yas
8   0.0  1.0  0.0  177    60   22
6   0.0  1.0  0.0  190    80   25
16  1.0  0.0  0.0  193    90   23
4   0.0  1.0  0.0  129    38   12
2   0.0  1.0  0.0  135    34   10
5   0.0  1.0  0.0  180    90   30
17  1.0  0.0  0.0  187    80   27
9   0.0  0.0  1.0  185   105   33
7   0.0  1.0  0.0  175    90   35
18  1.0  0.0  0.0  183    88   28
3   0.0  1.0  0.0  133    30    9
0   0.0  1.0  0.0  130    30   10
15  1.0  0.0  0.0  174    70   47
12  0.0  0.0  1.0  160    58   39
x_test :
     fr   tr   us  boy  kilo  yas
20  1.0  0.0  0.0  164    66   32
10  0.0  0.0  1.0  165    55   27
14  0.0  0.0  1.0  167    62   55
13  0.0  0.0  1.0  162    59   41
1   0.0  1.0  0.0  125    36   11
21  1.0  0.0  0.0  166    56   42
11  0.0  0.0  1.0  155    50   44
19  1.0  0.0  0.0  159    40   29
y_train :
    cinsiyet
8        0.0
6        1.0
16       1.0
4        1.0
2        0.0
5        1.0
17       1.0
9        1.0
7        1.0
18       1.0
3        0.0

## Verilerin Ölçeklenmesi

In [13]:
'''
Bu kod parçası, StandardScaler kullanarak eğitim ve test verilerini ölçeklendirir. 
StandardScaler, verileri standartlaştırarak her özelliğin ortalamasını 0 ve standart sapmasını 1 yapar. 
'''
from sklearn.preprocessing import StandardScaler
# Bu satır, scikit-learn kütüphanesinden StandardScaler sınıfını içe aktarır. Bu sınıf, verileri standartlaştırmak için kullanılır.
sc=StandardScaler()
# StandardScaler sınıfından bir örnek oluşturur. Bu örnek, fit edilip dönüştürülecek veriler için kullanılacaktır.
X_train=sc.fit_transform(x_train)
'''
fit_transform(x_train): StandardScaler'ı x_train veri seti üzerinde fit eder ve ardından bu veri setini dönüştürür. 
Bu, x_train veri setinin her bir özelliğini standartlaştırır (ortalaması 0, standart sapması 1 olacak şekilde).
'''
X_test=sc.fit_transform(x_test)
'''
transform(x_test): StandardScaler'ı önceden fit edilen (eğitilen) parametrelerle x_test veri setine uygular. Bu, test verilerini aynı ölçekte standartlaştırır.
Bu adımda sadece transform kullanılır, çünkü fit_transform kullanmak test verisinin eğitim verisine göre farklı bir ölçeklendirilmesine yol açabilir.
Eğitim ve test verilerinin aynı ölçekte olması gerekmektedir.
'''

"\ntransform(x_test): StandardScaler'ı önceden fit edilen (eğitilen) parametrelerle x_test veri setine uygular. Bu, test verilerini aynı ölçekte standartlaştırır.\nBu adımda sadece transform kullanılır, çünkü fit_transform kullanmak test verisinin eğitim verisine göre farklı bir ölçeklendirilmesine yol açabilir.\nEğitim ve test verilerinin aynı ölçekte olması gerekmektedir.\n"

In [14]:
from sklearn.linear_model import LinearRegression # Bu sınıf, doğrusal regresyon modeli oluşturmak için kullanılır.
regressor=LinearRegression() # LinearRegression sınıfından bir örnek oluşturur. Bu örnek, regresyon modelini temsil eder ve modelin özelliklerini ve metodlarını içerir.
regressor.fit(x_train,y_train)
'''
fit(x_train, y_train): Bu metot, doğrusal regresyon modelini eğitim verileri (x_train) ve hedef değişkenler (y_train) ile eğitir.
x_train: Eğitim verisi olarak kullanılan özellikler (features). Bu veriler, modelin bağımsız değişkenleridir.
y_train: Eğitim verisi olarak kullanılan hedef değişkenler (labels). Bu veriler, modelin bağımlı değişkenleridir.
fit metodu, verilen eğitim verilerini kullanarak modelin parametrelerini (ağırlıklar ve sapma) öğrenir.
'''

# şimdi tahmin işlemini yapacağız
y_pred=regressor.predict(x_test)
'''
predict(x_test): Bu metot, eğitilmiş model kullanılarak x_test veri seti için tahminler yapar.
x_test: Test verisi olarak kullanılan özellikler (features). Bu veriler, modelin bağımsız değişkenleridir.
y_pred: Bu değişken, modelin x_test verilerine karşılık olarak yaptığı tahminleri tutar. Tahmin edilen hedef değişkenler (labels) burada saklanır.
'''
print(y_pred) # - gelmiş olan sonuçları yanlış tahminde bulunmuş olarak değerlendirebiliriz

[[ 0.98720204]
 [-0.12036863]
 [ 0.05009703]
 [ 0.07137418]
 [ 0.72473935]
 [ 0.64615044]
 [-0.03567453]
 [ 0.32612171]]


In [15]:
print(y_test)

    cinsiyet
20       0.0
10       0.0
14       0.0
13       0.0
1        1.0
21       0.0
11       0.0
19       0.0


## Çıktıları görselleştirerek kaydetme


In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

def Kayit(variables):
    # "output" klasörünün yolu
    output_dir = 'output'
    
    # Klasör yoksa oluştur
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    # Her bir değişkeni görselleştirip kaydetme işlemi
    for var_name, var_data in variables.items():
        # Değişkeni DataFrame'e dönüştürme (eğer değilse)
        if not isinstance(var_data, pd.DataFrame):
            var_data = pd.DataFrame(var_data)
    
        # DataFrame'i bir ısı haritası olarak görselleştirme
        plt.figure(figsize=(5, len(var_data) // 2))
        sns.heatmap(var_data, annot=True, cmap="coolwarm", cbar=False, annot_kws={"size": 10})
    
        # Görseli "output" klasörüne değişken adıyla bir dosyaya kaydetme
        file_path = os.path.join(output_dir, f'{var_name}.png')
        plt.savefig(file_path, bbox_inches='tight')
        plt.close() 
    
    print("Tüm değişkenler görselleştirilip dosyalara kaydedildi.")


In [17]:
# Görselleştirmek ve kaydetme işlemi
variables = {
    "s": s,
    "s2": s2,
    "x_train": x_train,
    "x_test": x_test,
    "y_train": y_train,
    "y_test": y_test,
    "X_train": X_train,
    "X_test": X_test,
    "y_pred": y_pred
}
Kayit(variables)

Tüm değişkenler görselleştirilip dosyalara kaydedildi.


1. Kütüphanelerin İçe Aktarılması:,
* pandas (pd): Veri manipülasyonu ve analizi için kullanılır.
* matplotlib.pyplot (plt): Veri görselleştirme için kullanılır.
* seaborn (sns): Matplotlib üzerine kurulu bir kütüphane olup, istatistiksel grafikler oluşturmak için kullanılır.
2. Her Bir Değişkeni Görselleştirme ve Kaydetme:
* for döngüsü ile sözlükteki her bir değişkeni (anahtar-değer çiftini) işleme alıyoruz.
* var_name değişken adını, var_data ise değişkenin kendisini temsil eder.
* isinstance(var_data, pd.DataFrame): Eğer var_data bir DataFrame değilse, pd.DataFrame(var_data) ile onu bir DataFrame'e dönüştürüyoruz. Bu, tüm verilerin aynı formatta olmasını sağlar.
3. Isı Haritası Oluşturma:
* plt.figure(figsize=(5, len(var_data) // 2)): Görselin boyutunu ayarlıyoruz. Genişlik 5, yükseklik ise veri uzunluğunun yarısı olacak şekilde ayarlanır. Bu, her veri setinin boyutuna göre uygun bir görsel boyutu sağlar.
* sns.heatmap(var_data, annot=True, cmap="coolwarm", cbar=False, annot_kws={"size": 10}): Seaborn kütüphanesi kullanılarak bir ısı haritası oluşturuyoruz.
    * var_data: Görselleştirilecek veri.
    * annot=True: Hücrelerin içine veri değerlerini yazdırır.
    * cmap="coolwarm": Isı haritası için kullanılan renk paleti. "coolwarm" mavi ve kırmızı tonlarını içerir.
    * cbar=False: Renk çubuğunu gizler.
    * annot_kws={"size": 10}: Hücrelerdeki yazı boyutunu ayarlar.
4. Görseli Kaydetme:
* bbox_inches='tight': Görselin etrafındaki boşlukları minimuma indirir ve sıkıştırılmış bir şekilde kaydedilmesini sağlar.
* plt.close(): Mevcut çizimi kapatır. Bu, bir sonraki çizim için temiz bir başlangıç yapmamızı sağlar ve bellekte gereksiz yer kaplamayı önler.

## Boy Tahmini yapacağız

* Boy kolonunun sağ ve solundakileri 1 dataFrame haline getireceğiz ve boy da tek başına bir y kolonu olarak çıkacak

In [18]:
boy=s2.iloc[:,3:4].values # bağımlı değişkenleri içeren kolonum
print(boy)
sol=s2.iloc[:,:3]
sag=s2.iloc[:,4:]
veri=pd.concat([sol,sag],axis=1) # bağımsız değişkenleri içeren veri kümem

[[130]
 [125]
 [135]
 [133]
 [129]
 [180]
 [190]
 [175]
 [177]
 [185]
 [165]
 [155]
 [160]
 [162]
 [167]
 [174]
 [193]
 [187]
 [183]
 [159]
 [164]
 [166]]


In [19]:
x_train_boy,x_test_boy , y_train_boy,y_test_boy=train_test_split(veri,boy,test_size=0.33,random_state=0)
r2=LinearRegression()
r2.fit(x_train_boy,y_train_boy)
y_pred_boy=r2.predict(x_test_boy)
# x_test_boy dan y_test_boy verilerini tahmin edecek ve tahminler y_pred_boy

In [20]:
# Görselleştirmek ve kaydetme işlemi
variables = {
    "boy": boy,
    "sol": sol,
    "sag": sag,
    "veri": veri,
    "x_train_boy": x_train_boy,
    "x_test_boy": x_test_boy,
    "y_train_boy": y_train_boy,
    "y_test_boy": y_test_boy,
    "y_pred_boy": y_pred_boy
}
Kayit(variables)

Tüm değişkenler görselleştirilip dosyalara kaydedildi.


## Backward Elimination
* Amacımız hangi değişken sistemin yapısını daha fazla bozuyorsa onu sistemden çıkarmak.

In [24]:
import statsmodels.api as sm
X=np.append(arr=np.ones((22,1)).astype(int),values=veri,axis=1)
# 22 satır 1 sütundan oluşan dizi oluştur , values=veri demek veri dizisine ekle et demek, axis=1 demek sütun olarak ekle demek
print(X)

[[  1.   0.   1.   0.  30.  10.   1.]
 [  1.   0.   1.   0.  36.  11.   1.]
 [  1.   0.   1.   0.  34.  10.   0.]
 [  1.   0.   1.   0.  30.   9.   0.]
 [  1.   0.   1.   0.  38.  12.   1.]
 [  1.   0.   1.   0.  90.  30.   1.]
 [  1.   0.   1.   0.  80.  25.   1.]
 [  1.   0.   1.   0.  90.  35.   1.]
 [  1.   0.   1.   0.  60.  22.   0.]
 [  1.   0.   0.   1. 105.  33.   1.]
 [  1.   0.   0.   1.  55.  27.   0.]
 [  1.   0.   0.   1.  50.  44.   0.]
 [  1.   0.   0.   1.  58.  39.   0.]
 [  1.   0.   0.   1.  59.  41.   0.]
 [  1.   0.   0.   1.  62.  55.   0.]
 [  1.   1.   0.   0.  70.  47.   1.]
 [  1.   1.   0.   0.  90.  23.   1.]
 [  1.   1.   0.   0.  80.  27.   1.]
 [  1.   1.   0.   0.  88.  28.   1.]
 [  1.   1.   0.   0.  40.  29.   0.]
 [  1.   1.   0.   0.  66.  32.   0.]
 [  1.   1.   0.   0.  56.  42.   0.]]


In [25]:
X_l=veri.iloc[:,[0,1,2,3,4,5]].values
X_l=np.array(X_l,dtype=float)
model=sm.OLS(boy,X_l).fit() # bu sayede hangi değişkenin ne kadar etki ettiğini öğreniyoruz
'''
sm.OLS(boy, X_l):

    sm.OLS: statsmodels kütüphanesinde OLS modelini tanımlayan sınıftır.
    boy: Hedef değişken (bağımlı değişken). Modelin tahmin etmeye çalıştığı değeri temsil eder.
    X_l: Özellikler matrisi (bağımsız değişkenler). Modelin hedef değişkeni tahmin etmek için kullandığı verileri temsil eder.
    Bu kısım, bir OLS model nesnesi oluşturur, ancak model henüz eğitilmemiştir.

.fit():

    fit metodu, modeli verilen veriler üzerinde eğitir.
    Bu işlem, model parametrelerini (örneğin, regresyon katsayılarını) en iyi şekilde tahmin etmeye çalışır.
    .fit() metodunu çağırdıktan sonra, model değişkeni eğitilmiş model nesnesini içerir.
'''
print(model.summary()) # burada " P>|t|" değerine bakıyoruz ne kadar düşükse bizim için o kadar iyidir. Diğerlerinden önümüzdeki derslerde bahsedecekmiş

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Fri, 19 Jul 2024   Prob (F-statistic):           5.41e-07
Time:                        14:06:10   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.0

In [26]:
# en yüksek değeri vermiş olan 4. elemanı eliyorum
X_l=veri.iloc[:,[0,1,2,3,5]].values
X_l=np.array(X_l,dtype=float)
model=sm.OLS(boy,X_l).fit()
print(model.summary()) # x5 kabul edilebilir ama istersen onu da çıkartabliirsin.

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Fri, 19 Jul 2024   Prob (F-statistic):           9.32e-08
Time:                        14:09:32   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.6583      6.734     17.175      0.0