In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# verileri okuyalım
veriler=pd.read_csv('input/veriler.csv')
print(veriler)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k


## Veri Ön İşleme

In [3]:
boy=veriler[['boy']]
boyKilo=veriler[['boy','kilo']]
print(boyKilo)

    boy  kilo
0   130    30
1   125    36
2   135    34
3   133    30
4   129    38
5   180    90
6   190    80
7   175    90
8   177    60
9   185   105
10  165    55
11  155    50
12  160    58
13  162    59
14  167    62
15  174    70
16  193    90
17  187    80
18  183    88
19  159    40
20  164    66
21  166    56


### Eksik Veriler
* sci - kit learn

In [4]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
'''
from sklearn.impute import SimpleImputer:

    Bu satır, scikit-learn kütüphanesinin impute modülünden SimpleImputer sınıfını içe aktarır. Bu sınıf, eksik verileri belirli bir stratejiye göre doldurmak için kullanılır.

imputer = SimpleImputer(missing_values=np.nan, strategy='mean'):

    SimpleImputer(missing_values=np.nan, strategy='mean'): Bu, SimpleImputer sınıfından bir örnek oluşturur.
        missing_values=np.nan: Eksik değerlerin NaN (Not a Number) olduğunu belirtir. Yani, NaN olan hücreler eksik veri olarak kabul edilir.
        strategy='mean': Eksik değerlerin doldurulma stratejisini belirtir. Burada, eksik değerler ilgili sütunun " ortalama değeri " ile doldurulacaktır.
'''

'\nfrom sklearn.impute import SimpleImputer:\n\n    Bu satır, scikit-learn kütüphanesinin impute modülünden SimpleImputer sınıfını içe aktarır. Bu sınıf, eksik verileri belirli bir stratejiye göre doldurmak için kullanılır.\n\nimputer = SimpleImputer(missing_values=np.nan, strategy=\'mean\'):\n\n    SimpleImputer(missing_values=np.nan, strategy=\'mean\'): Bu, SimpleImputer sınıfından bir örnek oluşturur.\n        missing_values=np.nan: Eksik değerlerin NaN (Not a Number) olduğunu belirtir. Yani, NaN olan hücreler eksik veri olarak kabul edilir.\n        strategy=\'mean\': Eksik değerlerin doldurulma stratejisini belirtir. Burada, eksik değerler ilgili sütunun " ortalama değeri " ile doldurulacaktır.\n'

In [5]:
# Eğer elimdeki veri setinde yas sütununda eksik olsaydı o kısmı ortalama değer ( mean ) ile doldurmuş olacaktım
Yas=veriler.iloc[:,1:4].values
imputer=imputer.fit(Yas[:,1:4])
print(Yas)

[[130  30  10]
 [125  36  11]
 [135  34  10]
 [133  30   9]
 [129  38  12]
 [180  90  30]
 [190  80  25]
 [175  90  35]
 [177  60  22]
 [185 105  33]
 [165  55  27]
 [155  50  44]
 [160  58  39]
 [162  59  41]
 [167  62  55]
 [174  70  47]
 [193  90  23]
 [187  80  27]
 [183  88  28]
 [159  40  29]
 [164  66  32]
 [166  56  42]]


## Regresyon oluşturabilmek için numeric değerlere ihtiyacım var bu sebepten cinsiyet ve üşke kolonlarındaki değerleri değiştireceğiz<br>
## Encoding kullanacağız.<br>
* encoder: Kategorik -> Numeric

### Cinsiyet için :

In [6]:
# cinsiyet yerine c şeklinde isimlendirdik
c=veriler.iloc[:,-1:].values
'''
veriler.iloc[:,-1:]:

    iloc[] yöntemi, Pandas DataFrame'deki satır ve sütunları konumlarına göre seçmeye yarar.
    : ifadesi, tüm satırları seçtiğimizi belirtir.
    -1: ifadesi, en son sütunu seçer. : kullanımıyla birlikte en sondan başlayarak (yalnızca bir sütun olduğu için) bu sütunu seçer.

Bu adımda, veriler DataFrame'inin tüm satırlarının son sütunu seçiliyor.

.values:

    .values özelliği, Pandas DataFrame'i veya Serisini bir NumPy dizisine dönüştürür.

Bu adımda, seçilen son sütunu bir NumPy dizisi haline getiriyoruz.
'''
print(c)

[['e']
 ['e']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['k']
 ['k']]


In [7]:
from sklearn import preprocessing # Bu modül, veri ön işleme (preprocessing) işlemleri için çeşitli araçlar sunar.
le=preprocessing.LabelEncoder()
# LabelEncoder sınıfından bir örnek oluşturuyoruz. LabelEncoder, kategorik verileri sayısal verilere dönüştürmek için kullanılır.
# Örneğin, ["kırmızı", "yeşil", "mavi"] gibi kategorik değerleri [0, 1, 2] gibi sayısal değerlere dönüştürür.
c[:,-1]=le.fit_transform(veriler.iloc[:,-1])
'''
c[:,-1] = le.fit_transform(veriler.iloc[:,-1]):

    veriler.iloc[:,-1]: Bu, veriler DataFrame'inin son sütununu seçer. iloc yöntemi, DataFrame'in belirli bir dilimini seçmek için kullanılır.
    le.fit_transform(...): fit_transform yöntemi, önce etiket kodlayıcısını kategorik verilerle eğitir (fit), ardından bu verileri sayısal değerlere dönüştürür (transform).
    c[:,-1] = ...: c NumPy dizisinin son sütununa, dönüştürülmüş sayısal değerler atanır.
'''
print(c)

[[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]


In [8]:
ohe=preprocessing.OneHotEncoder()
c=ohe.fit_transform(c).toarray()
'''
Bu kod parçası, LabelEncoder ile sayısal değerlere dönüştürülmüş olan kategorik verileri, OneHotEncoder kullanarak tekil (one-hot) kodlamaya dönüştürüyor. Adım adım açıklayalım:
ohe = preprocessing.OneHotEncoder():

    OneHotEncoder sınıfından bir örnek oluşturuyoruz. OneHotEncoder, kategorik verileri ikili (binary) vektörlere dönüştürmek için kullanılır. 
    Örneğin, 0, 1 ve 2 gibi sayısal kategorileri şu şekilde vektörlere dönüştürür: [1,0,0], [0,1,0] ve [0,0,1].

c = ohe.fit_transform(c).toarray():

    fit_transform(c): OneHotEncoder'ı veri seti c ile eğitir (fit) ve ardından bu verileri one-hot kodlamalı vektörlere dönüştürür (transform).
    toarray(): Bu, elde edilen sparse matrisini (seyrek matris) yoğun (dense) bir NumPy dizisine dönüştürür.
    Bu, verilerin kolayca işlenebilmesi ve analiz edilebilmesi için gereklidir.
'''
print(c)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


### Ülke için :

In [9]:
ulke=veriler.iloc[:,0:1].values
ulke[:,0]=le.fit_transform(veriler.iloc[:,0])
ohe=preprocessing.OneHotEncoder()
ulke=ohe.fit_transform(ulke).toarray()
print(ulke)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [10]:
# Numpy dizileri dataframe donusumu
sonuc=pd.DataFrame(data=ulke,index=range(22),columns=['fr','tr','us'])
sonuc2=pd.DataFrame(data=Yas,index=range(22),columns=['boy','kilo','yas'])
cinsiyet=veriler.iloc[:,-1].values
sonuc3=pd.DataFrame(data=c[:,:1],index=range(22),columns=['cinsiyet']) # hem 0 hem 1 kolonunu almamamız lazım o kısım çok önemli
print(sonuc3)

    cinsiyet
0        1.0
1        1.0
2        0.0
3        0.0
4        1.0
5        1.0
6        1.0
7        1.0
8        0.0
9        1.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       1.0
16       1.0
17       1.0
18       1.0
19       0.0
20       0.0
21       0.0


## DataFrame Birleştirme İşlemi

In [11]:
s=pd.concat([sonuc,sonuc2],axis=1)
'''
s = pd.concat([sonuc, sonuc2], axis=1):

    pd.concat(): pandas kütüphanesindeki concat fonksiyonu, iki veya daha fazla DataFrame'i birleştirmek için kullanılır.
    [sonuc, sonuc2]: Bu, birleştirilecek olan iki DataFrame'i içeren bir listedir.
    axis=1: Bu parametre, birleştirmenin sütun bazında yapılacağını belirtir. Yani, sonuc ve sonuc2 DataFrame'leri yatay olarak yan yana eklenir.
    s: Bu, birleştirilmiş yeni DataFrame'i tutan değişkendir.
'''
s2=pd.concat([s,sonuc3],axis=1)
print(s2)

     fr   tr   us  boy  kilo  yas  cinsiyet
0   0.0  1.0  0.0  130    30   10       1.0
1   0.0  1.0  0.0  125    36   11       1.0
2   0.0  1.0  0.0  135    34   10       0.0
3   0.0  1.0  0.0  133    30    9       0.0
4   0.0  1.0  0.0  129    38   12       1.0
5   0.0  1.0  0.0  180    90   30       1.0
6   0.0  1.0  0.0  190    80   25       1.0
7   0.0  1.0  0.0  175    90   35       1.0
8   0.0  1.0  0.0  177    60   22       0.0
9   0.0  0.0  1.0  185   105   33       1.0
10  0.0  0.0  1.0  165    55   27       0.0
11  0.0  0.0  1.0  155    50   44       0.0
12  0.0  0.0  1.0  160    58   39       0.0
13  0.0  0.0  1.0  162    59   41       0.0
14  0.0  0.0  1.0  167    62   55       0.0
15  1.0  0.0  0.0  174    70   47       1.0
16  1.0  0.0  0.0  193    90   23       1.0
17  1.0  0.0  0.0  187    80   27       1.0
18  1.0  0.0  0.0  183    88   28       1.0
19  1.0  0.0  0.0  159    40   29       0.0
20  1.0  0.0  0.0  164    66   32       0.0
21  1.0  0.0  0.0  166    56   4

## Verilerin Eğitilmesi ve Test İçin Bölünmesi

In [12]:
from sklearn.model_selection import train_test_split
# Bu satır, scikit-learn kütüphanesinden train_test_split fonksiyonunu içe aktarır. Bu fonksiyon, veri setlerini eğitim ve test setlerine ayırmak için kullanılır.
x_train,x_test , y_train,y_test=train_test_split(s,sonuc3,test_size=0.33,random_state=0)
'''
train_test_split(s, sonuc3, test_size=0.33, random_state=0): Bu, s ve sonuc3 veri setlerini eğitim ve test setlerine ayırır.

    s: Özellikleri (features) temsil eden DataFrame.
    sonuc3: Hedef değişkeni (labels) temsil eden DataFrame.
    test_size=0.33: Verilerin %33'ünün test setine, geri kalan %67'sinin eğitim setine ayrılacağını belirtir.
    random_state=0: Rastgelelik kontrolü için sabit bir rastgelelik durumunu belirler. Bu, aynı verilerle aynı sonuçları elde etmek için kullanılır.
'''
print("x_train :")
print(x_train)
print("x_test :")
print(x_test)
print("y_train :")
print(y_train)
print("y_test :")
print(y_test)

x_train :
     fr   tr   us  boy  kilo  yas
8   0.0  1.0  0.0  177    60   22
6   0.0  1.0  0.0  190    80   25
16  1.0  0.0  0.0  193    90   23
4   0.0  1.0  0.0  129    38   12
2   0.0  1.0  0.0  135    34   10
5   0.0  1.0  0.0  180    90   30
17  1.0  0.0  0.0  187    80   27
9   0.0  0.0  1.0  185   105   33
7   0.0  1.0  0.0  175    90   35
18  1.0  0.0  0.0  183    88   28
3   0.0  1.0  0.0  133    30    9
0   0.0  1.0  0.0  130    30   10
15  1.0  0.0  0.0  174    70   47
12  0.0  0.0  1.0  160    58   39
x_test :
     fr   tr   us  boy  kilo  yas
20  1.0  0.0  0.0  164    66   32
10  0.0  0.0  1.0  165    55   27
14  0.0  0.0  1.0  167    62   55
13  0.0  0.0  1.0  162    59   41
1   0.0  1.0  0.0  125    36   11
21  1.0  0.0  0.0  166    56   42
11  0.0  0.0  1.0  155    50   44
19  1.0  0.0  0.0  159    40   29
y_train :
    cinsiyet
8        0.0
6        1.0
16       1.0
4        1.0
2        0.0
5        1.0
17       1.0
9        1.0
7        1.0
18       1.0
3        0.0

## Verilerin Ölçeklenmesi

In [13]:
'''
Bu kod parçası, StandardScaler kullanarak eğitim ve test verilerini ölçeklendirir. 
StandardScaler, verileri standartlaştırarak her özelliğin ortalamasını 0 ve standart sapmasını 1 yapar. 
'''
from sklearn.preprocessing import StandardScaler
# Bu satır, scikit-learn kütüphanesinden StandardScaler sınıfını içe aktarır. Bu sınıf, verileri standartlaştırmak için kullanılır.
sc=StandardScaler()
# StandardScaler sınıfından bir örnek oluşturur. Bu örnek, fit edilip dönüştürülecek veriler için kullanılacaktır.
X_train=sc.fit_transform(x_train)
'''
fit_transform(x_train): StandardScaler'ı x_train veri seti üzerinde fit eder ve ardından bu veri setini dönüştürür. 
Bu, x_train veri setinin her bir özelliğini standartlaştırır (ortalaması 0, standart sapması 1 olacak şekilde).
'''
X_test=sc.fit_transform(x_test)
'''
transform(x_test): StandardScaler'ı önceden fit edilen (eğitilen) parametrelerle x_test veri setine uygular. Bu, test verilerini aynı ölçekte standartlaştırır.
Bu adımda sadece transform kullanılır, çünkü fit_transform kullanmak test verisinin eğitim verisine göre farklı bir ölçeklendirilmesine yol açabilir.
Eğitim ve test verilerinin aynı ölçekte olması gerekmektedir.
'''

"\ntransform(x_test): StandardScaler'ı önceden fit edilen (eğitilen) parametrelerle x_test veri setine uygular. Bu, test verilerini aynı ölçekte standartlaştırır.\nBu adımda sadece transform kullanılır, çünkü fit_transform kullanmak test verisinin eğitim verisine göre farklı bir ölçeklendirilmesine yol açabilir.\nEğitim ve test verilerinin aynı ölçekte olması gerekmektedir.\n"