In [1]:
import cv2
import numpy as np

In [2]:
# opencv fonts resim olarak da bulunan site link : https://www.codesofinterest.com/2017/07/more-fonts-on-opencv.html
font=cv2.FONT_HERSHEY_SIMPLEX
font1=cv2.FONT_HERSHEY_COMPLEX

In [3]:
img=cv2.imread("1.1 polygons.png.png")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
_,threshold=cv2.threshold(gray,240,255,cv2.THRESH_BINARY)
contours,_=cv2.findContours(threshold,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

In [6]:
# conturs lara yaklaşma işlemi uygulayacağız
# true şekil kapalı demek
for cnt in contours:
    epsilon=0.01*cv2.arcLength(cnt,True)
    approx=cv2.approxPolyDP(cnt,epsilon,True)# conturs lara yaklaşma işlemi uyguladık
    cv2.drawContours(img,[approx],0,(0),5)
    
    # 0 indis x i 1 indis y yi temsil edecek
    x=approx.ravel()[0]
    y=approx.ravel()[1]
    
    #ilk önce aprox tuttuğu değerleri görelim
    print(approx) # koordinatlar
    print(len(approx)) # kaç köşeli olduğu
    
    # if biloğuyla çokgen adlarını yazıcaz
    if len(approx)==3:
        cv2.putText(img,"Triangle",(x,y),font,1,(0))
    elif len(approx)==4:
        cv2.putText(img,"Rectangle",(x,y),font,1,(0))
    elif len(approx)==5:
        cv2.putText(img,"Pentagon",(x,y),font,1,(0))
    elif len(approx)==6:
        cv2.putText(img,"Hexagon",(x,y),font,1,(0))
    else:
        cv2.putText(img,"Elips",(x,y),font1,1,(0)) # farklı font olsun dedim

cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[  0   0]]

 [[  0 416]]

 [[719 416]]

 [[719   0]]]
4
[[[ 27 318]]

 [[ 35 301]]

 [[ 65 280]]

 [[144 268]]

 [[209 286]]

 [[231 307]]

 [[235 327]]

 [[219 352]]

 [[195 366]]

 [[118 377]]

 [[ 53 359]]

 [[ 31 338]]]
12
[[[385 245]]

 [[469 286]]

 [[469 368]]

 [[387 409]]

 [[303 368]]

 [[303 286]]]
6
[[[130  69]]

 [[197 201]]

 [[ 62 199]]]
3
[[[279  68]]

 [[434  67]]

 [[435 197]]

 [[280 198]]]
4
[[[610  53]]

 [[685 110]]

 [[656 205]]

 [[566 205]]

 [[537 110]]]
5


site link : https://www.educba.com/opencv-approxpolydp/
# OpenCV ApproxPolyDP'ye Giriş
Bir kontur şeklinin, daha az sayıda köşeden oluşan başka bir şekle, şekillerin konturları arasındaki mesafenin belirtilen hassasiyete eşit veya belirtilen hassasiyetten daha az olacağı şekilde yaklaşma işlemine, bir şeklin yaklaşıklaştırılması denir. kontur. Ve OpenCV'deki yerleşik bir işlev, çokgen eğrilerin şeklini, approxPolyDP() işlevi adı verilen belirtilen hassasiyete yaklaşmak için kullanılır ve approxPolyDP() işlevi, şekli giriş eğrisiyle aynı olan yaklaşık konturu döndürür ve bir şeklin yaklaşık şeklidir. Kontur, robotik alanında desenleri sınıflandırmak ve sahnelerin analizini yapmak için yaygın olarak kullanılmaktadır.

OpenCV'de approxPolyDP() işlevini tanımlamaya yönelik sözdizimi aşağıdaki gibidir:

approxPolyDP(giriş_eğrisi, epsilon, kapalı)

burada giriş_eğrisi, çevresinin belirtilen hassasiyetle yaklaşıklaştırılması gereken giriş çokgenini temsil eder,
epsilon, giriş çokgeninin şekil konturunun yaklaşımı ile orijinal giriş çokgeni arasındaki maksimum mesafeyi temsil eder ve

kapalı, yaklaşık eğri kapalıysa değeri doğru olan veya yaklaşık eğri kapalı değilse değeri yanlış olan bir Boolean değeridir.

OpenCV'de approxPolyDP() fonksiyonunun çalışması:<br>
* Belirli bir çokgenin konturunun şeklini orijinal çokgenin şekline belirli bir hassasiyetle yaklaşma işlemine konturun şeklinin yaklaşımı denir.<br>
* Bir kontur şeklinin yaklaşık olarak tahminini gerçekleştirmek için OpenCV'de approxPolyDP() işlevi adı verilen bir işlevden yararlanırız.<br>
* Bir konturun şekline yaklaşılması gereken bir çokgenin görüntüsü imread() fonksiyonu kullanılarak okunur.<br>
* Daha sonra giriş görüntüsü gri tonlamalı görüntüye dönüştürülür.<br>
* Daha sonra gri tonlamalı görüntüye eşikleme fonksiyonu uygulanarak ikili görüntüye dönüştürülür.<br>
* Daha sonra findContours() fonksiyonu kullanılarak görüntüde bulunan konturlar belirlenir.<br>
* Daha sonra görüntüde belirlenen konturların her biri için approxPolyDP() fonksiyonu uygulanarak görüntüde bulunan çokgenlerin şekli belirlenir.<br>
* Daha sonra konturların belirlenen şekli, DrawContours() fonksiyonu kullanılarak görüntü üzerine çizilir ve programın çıktısı olarak görüntülenir.

site link : https://docs.opencv.org/3.4/d4/d73/tutorial_py_contours_begin.html
# Konturlar nasıl çizilir?
Konturları çizmek için cv.drawContours fonksiyonu kullanılır. Sınır noktalarına sahip olmanız koşuluyla herhangi bir şekli çizmek için de kullanılabilir. İlk argümanı kaynak görüntüdür, ikinci argümanı bir Python listesi olarak iletilmesi gereken konturlardır, üçüncü argümanı konturların indeksidir (bireysel kontur çizerken kullanışlıdır. Tüm konturları çizmek için -1'i iletin) ve geri kalan argümanlar renk, kalınlıktır. vesaire.<br>
* Bir görüntüdeki tüm konturları çizmek için:<br>
cv.drawContours (img, konturlar, -1, (0,255,0), 3)<br>
* Bireysel bir kontur çizmek için 4. kontur deyin:<br>
cv.drawContours (img, konturlar, 3, (0,255,0), 3)<br>
* Ancak çoğu zaman aşağıdaki yöntem faydalı olacaktır:<br>
cnt = konturlar[4]<br>
cv.drawContours (img, [cnt], 0, (0,255,0), 3)<br>

# Numpy.ravel () <br> 
işlevleri, bitişik düzleştirilmiş diziyi (tüm giriş dizisi öğelerini içeren ve onunla aynı türde olan 1 boyutlu dizi) döndürür. Yalnızca ihtiyaç duyulması halinde bir kopyası yapılır. <br>
## Yani tüm sütunları satıra döküyor

# Sözdizimi: cv2.putText(image, text, org, font, fontScale, color[, kalınlık[, lineType[, BottomLeftOrigin]]])

Parametreler:
<br>resim: Üzerine metin çizilecek resimdir.
<br>text: Çizilecek metin dizisi.
<br>org: Görüntüdeki metin dizesinin sol alt köşesinin koordinatlarıdır. Koordinatlar iki değerden oluşan gruplar halinde temsil edilir, yani ( X koordinat değeri, Y koordinat değeri).
<br>Font: Font tipini belirtir. Yazı tipi türlerinden bazıları FONT_HERSHEY_SIMPLEX, FONT_HERSHEY_PLAIN, vb.'dir.
<br>fontScale: Yazı tipine özgü taban boyutuyla çarpılan yazı tipi ölçek faktörü.
<br>color: Çizilecek metin dizisinin rengidir. BGR için bir tuple geçiyoruz. örneğin: (255, 0, 0) mavi renk için.
<br>kalınlık: Çizginin px cinsinden kalınlığıdır .
<br>lineType: İsteğe bağlı bir parametredir. Kullanılacak hattın tipini verir.
<br>BottomLeftOrigin: Bu isteğe bağlı bir parametredir. Doğru olduğunda görüntü verilerinin kaynağı sol alt köşededir. Aksi halde sol üst köşededir.

Dönüş Değeri: Bir resim döndürür.