np.uint negatif sayılar yok demek
np.int ile farkı bu yani

In [1]:
import numpy as np

In [10]:
x=np.array([[[-2,-1,0,5],[9,4,5,-7]],[[-2,-1,0,5],[9,4,5,-7]]],np.int8)
print(x.shape) # satır ve sütun sayısını verir # ilk yazan derinliği
print(x.ndim) # n dimension yani kaç boyutlu olduğu
print(x.dtype)
print(x.size) # eleman sayısı
print(x.T) # devriğini alma # transpose

(2, 2, 4)
3
int8
16
[[[-2 -2]
  [ 9  9]]

 [[-1 -1]
  [ 4  4]]

 [[ 0  0]
  [ 5  5]]

 [[ 5  5]
  [-7 -7]]]
