In [2]:
import numpy as np

In [3]:
np.empty([3,3],np.uint8)# 3e 3lük boş dizi

array([[  2,   0,   0],
       [  0,   0,   0],
       [  0,   0, 112]], dtype=uint8)

In [5]:
y=np.full((3,3,3),fill_value=5,dtype=np.uint8) # derinliği 3 olan 3X3 lük dizi dedik # eğitimde dtype önce yazdı ama bende çıkan istek aşamasında böyleydi o yüzden böyle yaptım
print(y)

[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]


In [6]:
z=np.ones((2,5,5),dtype=np.uint8)
print(z)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [7]:
z=np.zeros((2,5,5),dtype=np.uint8)
print(z)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
