# şeritleri işleyip tek bir çizgi haline getireceğiz

In [1]:
import cv2
import numpy as np

In [2]:
img=cv2.imread("3.1 h_line.png.png")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [3]:
# Canny() fonkisyonuyla köşeleri bulacağuz
edges=cv2.Canny(gray,75,150) # resim , min değer , max değer

In [4]:
cv2.imshow("img",img)
cv2.imshow("gray",gray)
cv2.imshow("edges",edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
# line leri tespit edeceğiz
# cv2.HoughLines() fonkisyonu çok fazla cpu kullandığından aşşağıdakini kullanıyoruz
lines=cv2.HoughLinesP(edges,1,np.pi/180,50) #resim , ro , teta değerleri , threshold değerleri
print(lines)

[[[ 46  57 119  57]]

 [[162  62 234  62]]

 [[441 325 608 325]]

 [[442 320 603 320]]

 [[259 325 259 199]]

 [[264 320 264 195]]

 [[404 122 404  63]]

 [[409 216 409 150]]

 [[523 217 607 217]]

 [[522 222 602 222]]

 [[ 50 193  89 193]]

 [[ 45 198  90 198]]

 [[603 319 603 223]]

 [[608 324 608 218]]

 [[265 321 349 321]]

 [[260 326 350 326]]

 [[380  57 408  57]]

 [[321  57 369  57]]

 [[ 49 192  49 157]]

 [[ 44 197  44 158]]

 [[320  62 403  62]]

 [[199 198 250 198]]

 [[200 193 238 193]]

 [[177  57 205  57]]

 [[404 215 404 159]]

 [[ 77  62 105  62]]]


# HoughLines (dst, satırlar, 1, CV_PI/180, 150, 0, 0); // gerçek algılamayı çalıştırır
dst : Kenar dedektörünün çıkışı. Gri tonlamalı bir görüntü olmalıdır (aslında ikili bir görüntü olmasına rağmen)<br>
çizgiler : Parametreleri saklayacak bir vektör( r , θ )tespit edilen hatlardan<br>
rho : Parametrenin çözünürlüğüRpiksel cinsinden. 1 piksel kullanıyoruz .<br>
teta : Parametrenin çözünürlüğüθradyan cinsinden. 1 derece kullanıyoruz (CV_PI/180)<br>
eşik : Bir çizgiyi "*algılamak*" için minimum kesişme sayısı<br>
srn ve stn : Varsayılan parametreler sıfırdır. Daha fazla bilgi için OpenCV referansını kontrol edin.<br><br><br>

A. Standart Hough Dönüşümü

Bu, hemen hemen önceki bölümde anlattıklarımızdan oluşuyor. Sonuç olarak size çiftlerden oluşan bir vektör verir( θ ,Rθ)
OpenCV'de HoughLines() fonksiyonu ile uygulanır.
B. Olasılıksal Hough Hattı Dönüşümü

Hough Line Dönüşümünün daha verimli bir uygulaması. Tespit edilen hatların uç noktalarını çıktı olarak verir.(X0,sen0,X1,sen1)
OpenCV'de HoughLinesP() fonksiyonu ile uygulanır.

link : https://docs.opencv.org/3.4/d9/db0/tutorial_hough_lines.html

In [6]:
# line lerin bulunduğu konumları birleştirip çizgi oluşturmak için for döngüsü kullanacağız
for line in lines:
    x1,y1,x2,y2=line[0]
    # şimdi çizeceğiz
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)
            #resim,başlangıç değerleri , bitiş değerleri, renk,kalınlık

In [7]:
cv2.imshow("img",img)
cv2.imshow("gray",gray)
cv2.imshow("edges",edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
# çizgi boşluklarını doldurmak
lines=cv2.HoughLinesP(edges,1,np.pi/180,50,maxLineGap=180) # son parametre en fazla çizgi boşluğunu veriyoruz o mesafeye kadar olan boşlukları dolduruyor

In [9]:
for line in lines:
    x1,y1,x2,y2=line[0]
    # şimdi çizeceğiz
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)
cv2.imshow("img",img)
cv2.imshow("gray",gray)
cv2.imshow("edges",edges)
cv2.waitKey(0)
cv2.destroyAllWindows()