In [1]:
import numpy as np

Küp olarak düşün

In [4]:
# iki boyutlu 2 tane diziyi tek [] içinde yaz
x=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],np.int16)
print(x)
# çağırıken de ilk yazdığın hangi iki boyutlu olan ikinci yazdığın iki boyutlunun kaçıncısı üçüncü yazılan da tek boyutun kaçıncısı olduğu
print(x[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12
