In [1]:
import cv2
import numpy as np

In [2]:
canvas=np.zeros((512,512,3),dtype=np.uint8) # canvas tuval demek , np.zeros((boyut,boyut,kanal sayısı ),çizim yaparkenki veri tipimiz) da siyah bir alan ayır demek
print(canvas) 

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [3]:
def Gosterim(hangiCanvas):
    cv2.imshow("Canvas gözüküyor",hangiCanvas)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
Gosterim(canvas)

In [ ]:
canvas=np.zeros((512,512,3),dtype=np.uint8)+255 # diyerek siyahı beyaz yaptık
Gosterim(canvas)