In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# veri çekme
veriler=pd.read_csv('input/veriler.csv')
print(veriler)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k


In [3]:
# veri işleme
boy=veriler[['boy']]
print(boy)

    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166


In [4]:
class insan:
    boy=165
    def fonksiyon(self,b):
        return b*2
ben=insan()
print(ben.boy)
print(ben.fonksiyon(21))

165
42


In [5]:
# liste
l=[1,3,5]

## Eksik Veriler

In [6]:
eksikVeriler=pd.read_csv('input/eksikveriler.csv')
print(eksikVeriler) # gördüğün gibi eksik olanlar NaN

   ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k


In [7]:
# şimdi farklı farklı yollar var biz ortalamayı alıp onu yazmaya karar verdik ( eğitimdeki hoc. )
# fit ile öğretip transform ile yerine koyuyoruz
from sklearn.impute import SimpleImputer # kullanacak olduğumuz kütüphane bu class içinde bulunmakta
# şimdi bir obje tanımlayacağız
imputer=SimpleImputer(missing_values=np.nan,strategy='mean') # numpy kütüpphanesi sayesinde nan atananları al demiş olduk , strategy='mean' demek strateji olarak mean yani ortalama kullan demek
Yas=eksikVeriler.iloc[:,1:4].values # tüm satırlardan 1ve 3 dahil sütünları getir dedik
print(Yas)

[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [129.  38.  12.]
 [180.  90.  30.]
 [190.  80.  25.]
 [175.  90.  35.]
 [177.  60.  22.]
 [185. 105.  33.]
 [165.  55.  27.]
 [155.  50.  44.]
 [160.  58.  nan]
 [162.  59.  41.]
 [167.  62.  55.]
 [174.  70.  47.]
 [193.  90.  nan]
 [187.  80.  27.]
 [183.  88.  28.]
 [159.  40.  29.]
 [164.  66.  32.]
 [166.  56.  42.]]


In [8]:
imputer=imputer.fit(Yas[:,1:4]) # burada eğittik dedik ki yaşın 1den 4e kadar olan tüm satırlarını öğren ve bu öğrenme bizim belirlediğimiz strateji yani ort alıyor
Yas[:,1:4]=imputer.transform(Yas[:,1:4]) # bu şekilde öğrendiğini uygula dedik
print(Yas)

[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]


## Kategorik Veriler
String ifadeyi sayısal atama yaparak ayrıştırdık diye düşünebilirsin

In [9]:
# ülke kolonumuz katagorik kolonumuz bunun üzerinde değişiklik yapacağız
ulke=eksikVeriler.iloc[:,0:1].values
print(ulke)

[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]


In [10]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

sklearn (scikit-learn), Python dilinde popüler bir makine öğrenimi kütüphanesidir ve veri madenciliği, veri analizi ve veri manipülasyonu gibi birçok görevde kullanılır. preprocessing modülü, veri ön işleme aşamalarında kullanılan araçları içerir. Bu araçlardan biri de LabelEncoder sınıfıdır.

LabelEncoder, özellikle kategorik (sınıflandırma) verilerle çalışırken kullanışlıdır. Bu sınıf, kategorik verileri sayısal değerlere dönüştürmeye yardımcı olur. Çoğu makine öğrenimi algoritması, sayısal girdi bekler, bu nedenle kategorik verileri sayısal hale getirmek önemlidir.

In [12]:
ulke[:,0]=le.fit_transform(eksikVeriler.iloc[:,0])
print(ulke)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


Bu kod satırı, kategorik bir sütunu (belirli bir ülke adı gibi) içeren bir veri setinde, LabelEncoder'ı kullanarak bu kategorik sütunu sayısal değerlere dönüştürmeyi amaçlamaktadır. Bu işlem genellikle makine öğrenimi modellerine giriş verileri sağlarken kullanılır, çünkü çoğu makine öğrenimi algoritması, sayısal verilerle daha iyi çalışır.

İşte bu kodun ayrıntılı açıklaması:

* eksikVeriler.iloc[:,0]: Bu ifade, eksikVeriler adlı bir veri çerçevesindeki tüm satırları ve sadece ilk sütunu seçer. iloc kullanımı, konum indeksine dayalı seçim yapar.

* le.fit_transform(eksikVeriler.iloc[:,0]): Burada, seçilen sütunun değerlerini LabelEncoder ile dönüştürüyoruz. fit_transform yöntemi, hem dönüşümü öğrenir (fit) hem de veriyi dönüştürür (transform). Dönüştürülen değerler, orijinal kategorik değerlere karşılık gelen sayısal değerlerdir.

* ulke[:,0]: Bu ifade, ulke adlı bir array'in tüm satırlarını ve sadece ilk sütununu seçer. ulke muhtemelen daha önce tanımlanmış bir array veya veri çerçevesidir.

* ulke[:,0]=le.fit_transform(eksikVeriler.iloc[:,0]): Bu ifade, ulke array'inin ilk sütununu, eksikVeriler veri çerçevesindeki ilgili kategorik sütunun sayısal karşılıkları ile değiştirir.

Örneğin, eğer eksikVeriler veri çerçevesinde ilk sütun ülkeleri içeriyorsa, bu işlemle o ülkelerin isimleri LabelEncoder kullanılarak sayısal değerlere dönüştürülmüş olacaktır. Bu sayısal değerler, her bir ülkenin benzersiz bir sayıya atanmış olduğu sayısal temsili sağlar.

In [13]:
ohe=preprocessing.OneHotEncoder()
ulke=ohe.fit_transform(ulke).toarray()
print(ulke)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


Bu kod bloğu, OneHotEncoder'ı kullanarak kategorik bir sütunu (muhtemelen ülkeleri temsil eden bir sütun) one-hot encoding yöntemiyle dönüştürmeye yöneliktir. One-hot encoding, kategorik verileri sayısal formata dönüştürmenin bir yöntemidir ve özellikle makine öğrenimi modellerinde kullanılır.

İşte bu kodun adım adım açıklaması:

* preprocessing.OneHotEncoder(): Bu ifade, OneHotEncoder sınıfından bir nesne (ohe) oluşturur. OneHotEncoder, kategorik veriyi one-hot encoding yöntemiyle dönüştürmek için kullanılır.

* ohe.fit_transform(ulke): Bu ifade, OneHotEncoder'ı kullanarak ulke array'ini dönüştürür. fit_transform yöntemi, önce dönüşümü öğrenir (fit) ve ardından veriyi dönüştürür (transform). Bu adımların kombinasyonu, one-hot encoding işlemini gerçekleştirir.

* toarray(): Bu ifade, elde edilen sparse matrix'i (seyrek matris) yoğun bir array'e dönüştürür. One-hot encoding sıklıkla büyük ve seyrek matrislerle sonuçlanır, bu nedenle toarray() kullanılarak yoğun bir array'e çevrilir.

* ulke=ohe.fit_transform(ulke).toarray(): Bu ifade, one-hot encoding işlemi sonrasında elde edilen yoğun array'i ulke değişkenine atar, böylece ulke artık one-hot encoding ile temsil edilen kategorik veriyi içerir.

Sonuç olarak, bu kod bloğu, kategorik ülke verilerini one-hot encoding ile sayısal bir formata dönüştürmeyi amaçlar. Bu dönüşüm, her bir ülkeyi temsil eden kategorik değerleri, her bir ülkenin bulunduğu sütuna karşılık gelen bir 1 ve diğer sütunlara karşılık gelen 0'lar içeren bir vektöre dönüştürür. Bu tip bir dönüşüm, özellikle sınıflandırma modelleri gibi bazı makine öğrenimi algoritmaları için giriş verilerini hazırlarken yaygın olarak kullanılır.