In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# veri çekme
veriler=pd.read_csv('input/veriler.csv')
print(veriler)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k


In [3]:
# veri işleme
boy=veriler[['boy']]
print(boy)

    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166


In [4]:
class insan:
    boy=165
    def fonksiyon(self,b):
        return b*2
ben=insan()
print(ben.boy)
print(ben.fonksiyon(21))

165
42


In [5]:
# liste
l=[1,3,5]

## Eksik Veriler

In [6]:
eksikVeriler=pd.read_csv('input/eksikveriler.csv')
print(eksikVeriler) # gördüğün gibi eksik olanlar NaN

   ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k


In [7]:
# şimdi farklı farklı yollar var biz ortalamayı alıp onu yazmaya karar verdik ( eğitimdeki hoc. )
# fit ile öğretip transform ile yerine koyuyoruz
from sklearn.impute import SimpleImputer # kullanacak olduğumuz kütüphane bu class içinde bulunmakta
# şimdi bir obje tanımlayacağız
imputer=SimpleImputer(missing_values=np.nan,strategy='mean') # numpy kütüpphanesi sayesinde nan atananları al demiş olduk , strategy='mean' demek strateji olarak mean yani ortalama kullan demek
Yas=eksikVeriler.iloc[:,1:4].values # tüm satırlardan 1ve 3 dahil sütünları getir dedik
print(Yas)

[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [129.  38.  12.]
 [180.  90.  30.]
 [190.  80.  25.]
 [175.  90.  35.]
 [177.  60.  22.]
 [185. 105.  33.]
 [165.  55.  27.]
 [155.  50.  44.]
 [160.  58.  nan]
 [162.  59.  41.]
 [167.  62.  55.]
 [174.  70.  47.]
 [193.  90.  nan]
 [187.  80.  27.]
 [183.  88.  28.]
 [159.  40.  29.]
 [164.  66.  32.]
 [166.  56.  42.]]


In [8]:
imputer=imputer.fit(Yas[:,1:4]) # burada eğittik dedik ki yaşın 1den 4e kadar olan tüm satırlarını öğren ve bu öğrenme bizim belirlediğimiz strateji yani ort alıyor
Yas[:,1:4]=imputer.transform(Yas[:,1:4]) # bu şekilde öğrendiğini uygula dedik
print(Yas)

[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]


## Kategorik Veriler
String ifadeyi sayısal atama yaparak ayrıştırdık diye düşünebilirsin

In [9]:
# ülke kolonumuz katagorik kolonumuz bunun üzerinde değişiklik yapacağız
ulke=eksikVeriler.iloc[:,0:1].values
print(ulke)

[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]


In [10]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

sklearn (scikit-learn), Python dilinde popüler bir makine öğrenimi kütüphanesidir ve veri madenciliği, veri analizi ve veri manipülasyonu gibi birçok görevde kullanılır. preprocessing modülü, veri ön işleme aşamalarında kullanılan araçları içerir. Bu araçlardan biri de LabelEncoder sınıfıdır.

LabelEncoder, özellikle kategorik (sınıflandırma) verilerle çalışırken kullanışlıdır. Bu sınıf, kategorik verileri sayısal değerlere dönüştürmeye yardımcı olur. Çoğu makine öğrenimi algoritması, sayısal girdi bekler, bu nedenle kategorik verileri sayısal hale getirmek önemlidir.

In [11]:
ulke[:,0]=le.fit_transform(eksikVeriler.iloc[:,0])
print(ulke)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


Bu kod satırı, kategorik bir sütunu (belirli bir ülke adı gibi) içeren bir veri setinde, LabelEncoder'ı kullanarak bu kategorik sütunu sayısal değerlere dönüştürmeyi amaçlamaktadır. Bu işlem genellikle makine öğrenimi modellerine giriş verileri sağlarken kullanılır, çünkü çoğu makine öğrenimi algoritması, sayısal verilerle daha iyi çalışır.

İşte bu kodun ayrıntılı açıklaması:

* eksikVeriler.iloc[:,0]: Bu ifade, eksikVeriler adlı bir veri çerçevesindeki tüm satırları ve sadece ilk sütunu seçer. iloc kullanımı, konum indeksine dayalı seçim yapar.

* le.fit_transform(eksikVeriler.iloc[:,0]): Burada, seçilen sütunun değerlerini LabelEncoder ile dönüştürüyoruz. fit_transform yöntemi, hem dönüşümü öğrenir (fit) hem de veriyi dönüştürür (transform). Dönüştürülen değerler, orijinal kategorik değerlere karşılık gelen sayısal değerlerdir.

* ulke[:,0]: Bu ifade, ulke adlı bir array'in tüm satırlarını ve sadece ilk sütununu seçer. ulke muhtemelen daha önce tanımlanmış bir array veya veri çerçevesidir.

* ulke[:,0]=le.fit_transform(eksikVeriler.iloc[:,0]): Bu ifade, ulke array'inin ilk sütununu, eksikVeriler veri çerçevesindeki ilgili kategorik sütunun sayısal karşılıkları ile değiştirir.

Örneğin, eğer eksikVeriler veri çerçevesinde ilk sütun ülkeleri içeriyorsa, bu işlemle o ülkelerin isimleri LabelEncoder kullanılarak sayısal değerlere dönüştürülmüş olacaktır. Bu sayısal değerler, her bir ülkenin benzersiz bir sayıya atanmış olduğu sayısal temsili sağlar.

In [12]:
ohe=preprocessing.OneHotEncoder()
ulke=ohe.fit_transform(ulke).toarray()
print(ulke)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


Bu kod bloğu, OneHotEncoder'ı kullanarak kategorik bir sütunu (muhtemelen ülkeleri temsil eden bir sütun) one-hot encoding yöntemiyle dönüştürmeye yöneliktir. One-hot encoding, kategorik verileri sayısal formata dönüştürmenin bir yöntemidir ve özellikle makine öğrenimi modellerinde kullanılır.

İşte bu kodun adım adım açıklaması:

* preprocessing.OneHotEncoder(): Bu ifade, OneHotEncoder sınıfından bir nesne (ohe) oluşturur. OneHotEncoder, kategorik veriyi one-hot encoding yöntemiyle dönüştürmek için kullanılır.

* ohe.fit_transform(ulke): Bu ifade, OneHotEncoder'ı kullanarak ulke array'ini dönüştürür. fit_transform yöntemi, önce dönüşümü öğrenir (fit) ve ardından veriyi dönüştürür (transform). Bu adımların kombinasyonu, one-hot encoding işlemini gerçekleştirir.

* toarray(): Bu ifade, elde edilen sparse matrix'i (seyrek matris) yoğun bir array'e dönüştürür. One-hot encoding sıklıkla büyük ve seyrek matrislerle sonuçlanır, bu nedenle toarray() kullanılarak yoğun bir array'e çevrilir.

* ulke=ohe.fit_transform(ulke).toarray(): Bu ifade, one-hot encoding işlemi sonrasında elde edilen yoğun array'i ulke değişkenine atar, böylece ulke artık one-hot encoding ile temsil edilen kategorik veriyi içerir.

Sonuç olarak, bu kod bloğu, kategorik ülke verilerini one-hot encoding ile sayısal bir formata dönüştürmeyi amaçlar. Bu dönüşüm, her bir ülkeyi temsil eden kategorik değerleri, her bir ülkenin bulunduğu sütuna karşılık gelen bir 1 ve diğer sütunlara karşılık gelen 0'lar içeren bir vektöre dönüştürür. Bu tip bir dönüşüm, özellikle sınıflandırma modelleri gibi bazı makine öğrenimi algoritmaları için giriş verilerini hazırlarken yaygın olarak kullanılır.

## Verilerin Birleştirilmesi

In [13]:
# şimdi verileri dataFrame ile birleştiricez
# dataFrameleri indexi ve kolon başlıkları vardır diziden en büyük farkı budur
sonuc=pd.DataFrame(data=ulke,index=range(22),columns=['fr','tr','us'])
print(sonuc)

     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0


In [14]:
sonuc2=pd.DataFrame(data=Yas,index=range(22),columns=['boy','kilo','yas'])
print(sonuc2)

      boy   kilo    yas
0   130.0   30.0  10.00
1   125.0   36.0  11.00
2   135.0   34.0  10.00
3   133.0   30.0   9.00
4   129.0   38.0  12.00
5   180.0   90.0  30.00
6   190.0   80.0  25.00
7   175.0   90.0  35.00
8   177.0   60.0  22.00
9   185.0  105.0  33.00
10  165.0   55.0  27.00
11  155.0   50.0  44.00
12  160.0   58.0  28.45
13  162.0   59.0  41.00
14  167.0   62.0  55.00
15  174.0   70.0  47.00
16  193.0   90.0  28.45
17  187.0   80.0  27.00
18  183.0   88.0  28.00
19  159.0   40.0  29.00
20  164.0   66.0  32.00
21  166.0   56.0  42.00


In [15]:
cinsiyet=veriler.iloc[:,-1].values
print(cinsiyet)
sonuc3=pd.DataFrame(data=cinsiyet,index=range(22),columns=['cinsiyet'])
print(sonuc3)

['e' 'e' 'k' 'k' 'e' 'e' 'e' 'e' 'k' 'e' 'k' 'k' 'k' 'k' 'k' 'e' 'e' 'e'
 'e' 'k' 'k' 'k']
   cinsiyet
0         e
1         e
2         k
3         k
4         e
5         e
6         e
7         e
8         k
9         e
10        k
11        k
12        k
13        k
14        k
15        e
16        e
17        e
18        e
19        k
20        k
21        k


In [16]:
# şimdi bu dataları birleştireceğiz
s=pd.concat([sonuc,sonuc2])#böyle olunca alt alta ekleme yapıyor axis=1 verip yan yana yapıcaz
print(s)

     fr   tr   us    boy   kilo    yas
0   0.0  1.0  0.0    NaN    NaN    NaN
1   0.0  1.0  0.0    NaN    NaN    NaN
2   0.0  1.0  0.0    NaN    NaN    NaN
3   0.0  1.0  0.0    NaN    NaN    NaN
4   0.0  1.0  0.0    NaN    NaN    NaN
5   0.0  1.0  0.0    NaN    NaN    NaN
6   0.0  1.0  0.0    NaN    NaN    NaN
7   0.0  1.0  0.0    NaN    NaN    NaN
8   0.0  1.0  0.0    NaN    NaN    NaN
9   0.0  0.0  1.0    NaN    NaN    NaN
10  0.0  0.0  1.0    NaN    NaN    NaN
11  0.0  0.0  1.0    NaN    NaN    NaN
12  0.0  0.0  1.0    NaN    NaN    NaN
13  0.0  0.0  1.0    NaN    NaN    NaN
14  0.0  0.0  1.0    NaN    NaN    NaN
15  1.0  0.0  0.0    NaN    NaN    NaN
16  1.0  0.0  0.0    NaN    NaN    NaN
17  1.0  0.0  0.0    NaN    NaN    NaN
18  1.0  0.0  0.0    NaN    NaN    NaN
19  1.0  0.0  0.0    NaN    NaN    NaN
20  1.0  0.0  0.0    NaN    NaN    NaN
21  1.0  0.0  0.0    NaN    NaN    NaN
0   NaN  NaN  NaN  130.0   30.0  10.00
1   NaN  NaN  NaN  125.0   36.0  11.00
2   NaN  NaN  NaN  135.0 

In [17]:
s=pd.concat([sonuc,sonuc2],axis=1)
print(s)

     fr   tr   us    boy   kilo    yas
0   0.0  1.0  0.0  130.0   30.0  10.00
1   0.0  1.0  0.0  125.0   36.0  11.00
2   0.0  1.0  0.0  135.0   34.0  10.00
3   0.0  1.0  0.0  133.0   30.0   9.00
4   0.0  1.0  0.0  129.0   38.0  12.00
5   0.0  1.0  0.0  180.0   90.0  30.00
6   0.0  1.0  0.0  190.0   80.0  25.00
7   0.0  1.0  0.0  175.0   90.0  35.00
8   0.0  1.0  0.0  177.0   60.0  22.00
9   0.0  0.0  1.0  185.0  105.0  33.00
10  0.0  0.0  1.0  165.0   55.0  27.00
11  0.0  0.0  1.0  155.0   50.0  44.00
12  0.0  0.0  1.0  160.0   58.0  28.45
13  0.0  0.0  1.0  162.0   59.0  41.00
14  0.0  0.0  1.0  167.0   62.0  55.00
15  1.0  0.0  0.0  174.0   70.0  47.00
16  1.0  0.0  0.0  193.0   90.0  28.45
17  1.0  0.0  0.0  187.0   80.0  27.00
18  1.0  0.0  0.0  183.0   88.0  28.00
19  1.0  0.0  0.0  159.0   40.0  29.00
20  1.0  0.0  0.0  164.0   66.0  32.00
21  1.0  0.0  0.0  166.0   56.0  42.00


In [18]:
s2=pd.concat([s,sonuc3],axis=1)
print(s2)

     fr   tr   us    boy   kilo    yas cinsiyet
0   0.0  1.0  0.0  130.0   30.0  10.00        e
1   0.0  1.0  0.0  125.0   36.0  11.00        e
2   0.0  1.0  0.0  135.0   34.0  10.00        k
3   0.0  1.0  0.0  133.0   30.0   9.00        k
4   0.0  1.0  0.0  129.0   38.0  12.00        e
5   0.0  1.0  0.0  180.0   90.0  30.00        e
6   0.0  1.0  0.0  190.0   80.0  25.00        e
7   0.0  1.0  0.0  175.0   90.0  35.00        e
8   0.0  1.0  0.0  177.0   60.0  22.00        k
9   0.0  0.0  1.0  185.0  105.0  33.00        e
10  0.0  0.0  1.0  165.0   55.0  27.00        k
11  0.0  0.0  1.0  155.0   50.0  44.00        k
12  0.0  0.0  1.0  160.0   58.0  28.45        k
13  0.0  0.0  1.0  162.0   59.0  41.00        k
14  0.0  0.0  1.0  167.0   62.0  55.00        k
15  1.0  0.0  0.0  174.0   70.0  47.00        e
16  1.0  0.0  0.0  193.0   90.0  28.45        e
17  1.0  0.0  0.0  187.0   80.0  27.00        e
18  1.0  0.0  0.0  183.0   88.0  28.00        e
19  1.0  0.0  0.0  159.0   40.0  29.00  

## Veri Bölme

In [19]:
# x bağımsız y bağımlı değişken olarak ilerleyeceğiz
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(s,sonuc3,test_size=0.33,random_state=0)

Python'daki scikit-learn kütüphanesinde bulunan train_test_split fonksiyonunu kullanarak verilerinizi eğitim ve test setlerine bölmek için kullanılır. Şu şekilde detaylandırabiliriz:

* s: Bu, özellik verilerinizdir ve muhtemelen bir DataFrame veya dizi benzeri bir nesnedir. Makine öğrenimi modeliniz için girdi özelliklerini içerir.

* sonuc3: Bu, tahmin etmeye çalıştığınız hedef verilerinizdir. Bu, muhtemelen tek bir sütun veya her satırdaki karşılık gelen hedef değerlerini içeren bir dizi olabilir.

* test_size=0.33: Bu parametre, test bölümünde kullanılacak veri yüzdesini belirtir. Bu durumda, 0.33 olarak ayarlanmıştır, bu da verinin %33'ünün test için, geri kalan %67'sinin ise eğitim için kullanılacağı anlamına gelir.

* random_state=0: Bu parametre, rasgele sayı üreteci için bir tohum (seed) değerini ayarlamak için kullanılır. Belirli bir rasgele tohumu ayarlamak, her seferinde bu kodu çalıştırdığınızda aynı bölünmeyi elde etmenizi sağlar, bu da sonuçlarınızın tekrarlanabilir olmasını sağlar. Bu durumda tohum değeri 0 olarak ayarlanmıştır.

train_test_split fonksiyonu dört set veri döndürür:

* x_train: Bu, eğitim setinizdir ve özellik verilerinizin bir alt kümesini içerir (s). Karşılık gelen hedef değerleri y_train içinde bulunur.

* x_test: Bu, test setinizdir ve özellik verilerinizin farklı bir alt kümesini içerir (s). Karşılık gelen hedef değerleri y_test içinde bulunur.

* y_train: Bu, eğitim setinizin hedef değerleridir. Bu, x_train içindeki eğitim özellik setinin karşılık gelen hedef değerlerini içerir.

* y_test: Bu, test setinizin hedef değerleridir. Bu, x_test içindeki test özellik setinin karşılık gelen hedef değerlerini içerir.

In [21]:
print('x_train : ',x_train)
print('x_test : ',x_test)
print('y_train : ',y_train)
print('y_test : ',y_test)

x_train :       fr   tr   us    boy   kilo    yas
8   0.0  1.0  0.0  177.0   60.0  22.00
6   0.0  1.0  0.0  190.0   80.0  25.00
16  1.0  0.0  0.0  193.0   90.0  28.45
4   0.0  1.0  0.0  129.0   38.0  12.00
2   0.0  1.0  0.0  135.0   34.0  10.00
5   0.0  1.0  0.0  180.0   90.0  30.00
17  1.0  0.0  0.0  187.0   80.0  27.00
9   0.0  0.0  1.0  185.0  105.0  33.00
7   0.0  1.0  0.0  175.0   90.0  35.00
18  1.0  0.0  0.0  183.0   88.0  28.00
3   0.0  1.0  0.0  133.0   30.0   9.00
0   0.0  1.0  0.0  130.0   30.0  10.00
15  1.0  0.0  0.0  174.0   70.0  47.00
12  0.0  0.0  1.0  160.0   58.0  28.45
x_test :       fr   tr   us    boy  kilo   yas
20  1.0  0.0  0.0  164.0  66.0  32.0
10  0.0  0.0  1.0  165.0  55.0  27.0
14  0.0  0.0  1.0  167.0  62.0  55.0
13  0.0  0.0  1.0  162.0  59.0  41.0
1   0.0  1.0  0.0  125.0  36.0  11.0
21  1.0  0.0  0.0  166.0  56.0  42.0
11  0.0  0.0  1.0  155.0  50.0  44.0
19  1.0  0.0  0.0  159.0  40.0  29.0
y_train :     cinsiyet
8         k
6         e
16        e
4 

## Öznitelik Ölçekleme

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler # objemi oluşturdum

In [24]:
# şimdi dönüştürmek istediğim sayısal değerleri alacağım
X_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)

TypeError: TransformerMixin.fit_transform() missing 1 required positional argument: 'X'