In [3]:
import numpy as np

# Numpy Arrys

In [4]:
matrixListesi=[[10,20,30],[40,50,60],[70,80,90]]

In [5]:
np.array(matrixListesi)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# arange

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# zeros , ones

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# linspaec = listede vermiş olduğun aralıkta kaç tane değer görmek istediğini verirsin 

In [15]:
np.linspace(0,50,100) # 0dan 50 ye kadar 100 tane aralarındaki fark eşit olan sayılar 

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

# eye = birim matris oluşturur

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# random

In [18]:
np.random.rand(4)

array([0.03079851, 0.41406479, 0.86005769, 0.5461121 ])

In [19]:
np.random.rand(3,3)

array([[0.95523587, 0.53047495, 0.87915882],
       [0.31367176, 0.23498962, 0.42161649],
       [0.34043315, 0.02912263, 0.8582523 ]])

In [20]:
np.random.randint(0,14)

6

In [21]:
np.random.randint(0,14,3)

array([2, 3, 3])

In [22]:
np.random.randint(0,14,(3,3))

array([[ 8,  0,  6],
       [ 4,  7,  8],
       [ 8,  1, 13]])