In [1]:
import numpy as np

In [2]:
benimDizim=np.arange(0,15)
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
benimDizim[3:7]=-2 # 3. index dahil 7. index hariç -2 yap demek

In [5]:
benimDizim


array([ 0,  1,  2, -2, -2, -2, -2,  7,  8,  9, 10, 11, 12, 13, 14])

# Diziden eleman alıp başka diziye koyup sonra o dizide o elemanları değiştirince orjinalinde de değişiyor

In [7]:
slicingDizisi=benimDizim[2:10]

In [8]:
slicingDizisi[:]=13

In [9]:
slicingDizisi

array([13, 13, 13, 13, 13, 13, 13, 13])

In [10]:
benimDizim

array([ 0,  1, 13, 13, 13, 13, 13, 13, 13, 13, 10, 11, 12, 13, 14])

# Değiştirmeme yolu : 


In [11]:
ornekDizi=np.arange(0,30)

In [12]:
ornekdiziCopy=ornekDizi.copy()

In [13]:
ornekdiziCopyAlım=ornekdiziCopy[3:13]

In [14]:
ornekdiziCopyAlım[5:12]=888

In [15]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
ornekdiziCopy

array([  0,   1,   2,   3,   4,   5,   6,   7, 888, 888, 888, 888, 888,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [17]:
ornekdiziCopyAlım

array([  3,   4,   5,   6,   7, 888, 888, 888, 888, 888])

# matrix

In [37]:
benimMatrixim=np.random.randint(0,14,(3,3))

In [38]:
benimMatrixim

array([[ 3,  3,  5],
       [13, 12, 12],
       [ 0, 11,  0]])

In [39]:
benimMatrixim[2][1]

11

In [40]:
benimMatrixim[2][1:]

array([11,  0])

In [45]:
benimNumpyDizim=np.arange(0,60,5)

In [49]:
YenibenimNumpyDizim=benimNumpyDizim.reshape(4,3)

In [50]:
YenibenimNumpyDizim[[0,2,3]]

array([[ 0,  5, 10],
       [30, 35, 40],
       [45, 50, 55]])

# Operasyonlar

In [55]:
yeniBirDizi=np.random.randint(1,100,20)

In [56]:
yeniBirDizi

array([95, 94, 14, 63, 11, 97, 82, 29, 78, 76, 14, 49, 67, 78, 13,  5, 79,
       85, 15, 27])

In [59]:
sonucDizisi=yeniBirDizi>53

In [60]:
yeniBirDizi[sonucDizisi]

array([95, 94, 63, 97, 82, 78, 76, 67, 78, 79, 85])

In [61]:
yeniBirDizi[yeniBirDizi>53]

array([95, 94, 63, 97, 82, 78, 76, 67, 78, 79, 85])

In [62]:
sonDizi=np.arange(0,24)

In [64]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [67]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [68]:
sonDizi/sonDizi

C:\Users\ibo_m\AppData\Local\Temp\ipykernel_20272\1954055075.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [69]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [70]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [71]:
np.min(sonDizi)

0